open-contracting/covid-19-procurement-explorer-public

package.json
src/assets/components/_table.scss
src/assets/components/_tabs.scss
src/assets/components/base-components.scss
src/assets/main.scss
src/components/countryProfile.js
src/layouts/Country.js
tailwind.config.js
yarn.lock

Country profile and tender table UI

---

.eslintrc.js
.gitignore
.prettierrc
package.json
yarn.lock

Code formatting and linting

---

src/assets/scss/components/_table.scss
src/components/country/CountryDataChart.js
src/components/country/tender.js
src/helpers/index.js
src/layouts/Country.js
src/layouts/TenderDetail.js
src/services/countryProfileServices.js
src/services/countryServices.js

-[x] Tender page new api integrate
-[x] Env file for api url

Tender api fix

---

src/assets/scss/custom/_news.scss
src/components/footer/footer.js
src/layouts/Blogs.js
src/layouts/BlogsDetail.js
src/layouts/Events.js
src/layouts/EventsDetail.js
src/layouts/Library.js
src/layouts/News.js
src/layouts/NewsDetail.js
src/layouts/Resources.js
src/layouts/Tags.js
tailwind.config.js

adding conditional rendering to blogs, events and resources page

---

package-lock.json
package.json
src/assets/scss/pages/_home.scss
src/helpers/index.js
src/layouts/pages/Blog/BlogsDetail.js
src/layouts/pages/Events/EventsDetail.js
src/layouts/pages/GlobalOverview/tabs/GlobalEquity.js
src/layouts/pages/Homepage/sections/LibrarySection.js
src/layouts/pages/News/NewsDetail.js
src/layouts/pages/Tender/TenderDetail.js
src/layouts/pages/share.js
src/services/countryContractMapServices.js
yarn.lock

adding share to share icons in CMS detail pages

---

src/assets/scss/pages/_home.scss
src/components/CountrySelector/CountrySelector.js
src/components/CurrencySwitcher/CurrencySwitcher.js
src/layouts/pages/CountryProfile/index.js
src/layouts/pages/CountryProfile/sections/CountryInfo.js
src/layouts/pages/Homepage/sections/WorldMapRace.js
src/layouts/pages/share.js

adding dropdown to country profile

---

src/components/Tables/TenderTable.js
src/layouts/pages/Tender/TenderDetail.js

-[x] Supplier profile tender table date column missing fix

-[x] Contract detail page fixes

---

src/assets/scss/components/_spinner.scss
src/assets/scss/components/base-components.scss
src/components/Loader/TableLoader.js
src/components/Tables/BuyerTable.js
src/components/Tables/SupplierTable.js
src/components/Tables/TenderTable.js
src/layouts/pages/Resources/index.js

-[x] Buyers and suppliers tab filter

-[x] Buyers and suppliers tab pagination

---

src/components/Tables/BuyerTable.js
src/components/Tables/SupplierTable.js
src/components/Tables/TenderTable.js
src/helpers/api.js
src/layouts/pages/Buyer/BuyerProfile.js
src/layouts/pages/Supplier/SupplierProfile.js
src/layouts/pages/Tender/TenderDetail.js

-[x] Buyer and supplier profile filter fix
-[x] Supplier and buyer tab filter fix
-[x] Contract detail page fixes

Filter fixes

---

package.json
src/components/Tables/InsightTable.js
src/layouts/pages/News/NewsDetail.js
yarn.lock

-[x] Insight table country filter

---

package.json
src/components/CountrySelector/CountrySelector.js
src/components/Tables/BuyerTable.js
src/components/Tables/ContractFilter.js
src/components/Tables/InsightTable.js
src/components/Tables/ProductTable.js
src/components/Tables/SupplierTable.js
src/components/Tables/TenderTable.js
src/helpers/api.js
src/helpers/general.js
src/hooks/useContractFilters.js
src/layouts/pages/Product/sections/MainChart.js
yarn.lock

CP-204 Sorting functionality in Tender table

---

src/constants/Tab.js
src/layouts/_partials/footer.js
src/layouts/pages/CountryProfile/index.js
src/layouts/pages/GlobalOverview/index.js
src/layouts/pages/Homepage/index.js
src/layouts/pages/Homepage/sections/HomeBanner.js
src/layouts/pages/Homepage/sections/MainVisualization.js
src/layouts/pages/StaticPage/CmsPageContent.js
src/layouts/pages/Tender/TenderDetail.js

CP-236 Home page Sources section implementation

---

src/assets/scss/components/_tabs.scss
src/assets/scss/custom/custom.scss
src/components/Charts/BarChart/BarChartRace.js
src/components/Charts/CombinedChart/CombinedChart.js
src/components/Tables/BuyerTable.js
src/components/Tables/ContractTable.js
src/components/Tables/ProductTable.js
src/components/Tables/ShortTenderTable.js
src/components/Tables/SupplierTable.js
src/components/Utilities/CardContainer.js
src/components/Utilities/ChartFooter.js
src/components/Utilities/ContractViewSwitcher.js
src/components/Visualizations/ContractRedFlags.js
src/components/Visualizations/ContractsCorrelation.js
src/components/Visualizations/GlobalSuppliers.js
src/layouts/pages/Blog/index.js
src/layouts/pages/CountryProfile/index.js
src/layouts/pages/CountryProfile/sections/CountryInfo.js
src/layouts/pages/CountryProfile/sections/CountryMapElement.js
src/layouts/pages/GlobalOverview/modal/VisualizationModal.js
src/layouts/pages/GlobalOverview/tabs/GlobalData.js
src/layouts/pages/Homepage/sections/MainVisualization.js
src/layouts/pages/Tender/TenderDetail.js

-[x] Renaming the texts
-[x] Red Flag Bug fixes on table and contract detail
-[x] Total spending covid case api implemented in country detail page
-[x] Death case key added in Contract Correlation charts
-[x] View more link added in global suppliers and red flag section

CP-270 Bug Reported UI fixes

---

src/assets/scss/custom/custom.scss
src/components/Charts/BarChart/BarChartRace.js
src/components/GlobalMap/GlobalMap.js
src/components/Modals/EmbeddedModal.js
src/components/Utilities/PerCapitaSwitcher.js
src/components/Visualizations/BuyerTrend.js
src/components/Visualizations/ContractTrend.js
src/components/Visualizations/DirectOpenContractTrend.js
src/components/Visualizations/SupplierTrend.js
src/components/Visualizations/WorldMap.js
src/components/Visualizations/WorldTimelineMap.js
src/components/Visualizations/WorldTimelineRaceBarMap.js
src/layouts/pages/GlobalOverview/modal/VisualizationModal.js

CP-284 Per capita implementation

---

src/assets/scss/custom/_resources.scss
src/components/CountryPartnerSlider/CountryPartnerSlider.js
src/layouts/pages/Buyer/BuyerProfile.js
src/layouts/pages/Contract/ContractDetail.js
src/layouts/pages/Events/index.js
src/layouts/pages/Resources/ResourceDetail.js
src/layouts/pages/Supplier/SupplierProfile.js

-[x] Add prooflink which leads to the country public procurement portal.
-[x] Add topic & language section in resource detail page
-[x] country profile - partners section link to add
-[x] remove product timeline on the top of each buyer profile

UI bug fixes

---

src/components/Tables/OverallStatisticsTable.js
src/layouts/pages/Contract/ContractDetail.js
src/layouts/pages/CountryProfile/index.js
src/layouts/pages/CountryProfile/tabs/CountryMethodology.js
src/layouts/pages/Events/EventDetail.js
src/layouts/pages/StaticPage/CmsPageContent.js
src/layouts/pages/StaticPage/index.js

CP-303 Methodology: Flash of incorrect content

---

src/components/Tables/BuyerTable.js
src/components/Tables/ContractTable.js
src/components/Tables/InsightTable.js
src/components/Tables/ProductTable.js
src/components/Tables/SupplierTable.js
src/hooks/useTableSorting.js
src/layouts/pages/Contract/AwardedItemsTable.js
src/layouts/pages/GlobalOverview/tabs/GlobalInsights.js

-[x] Product Profile Table
-[x] Contract Table
-[x] Buyer and Supplier Table
-[x] Insights Table

Sorting Table Dynamic

---

src/components/Charts/SankeyChart/SankeyChart.js
src/components/Charts/StackedChart/StackedChart.js
src/components/CountrySelector/CountrySelector.js
src/components/SimpleBarListSection/SimpleBarListChart.js
src/components/Visualizations/GlobalSuppliers.js
src/components/Visualizations/ProductsTimeline.js
src/components/Visualizations/TotalContracts.js
src/components/Visualizations/TotalSpending.js

Country Selector Sort UI

---

src/components/Tables/OverallStatisticsTable.js

CP-356-re Hide "Contract status" section

---

package.json
src/components/Tables/InsightTable.js
src/components/Tables/OverallStatisticsTable.js
src/components/Visualizations/Buyers.js
src/components/Visualizations/Charts/SimpleBarListSection/SimpleBarListChart.js
src/components/Visualizations/ContractsCorrelation.js
src/components/Visualizations/DirectOpen.js
src/components/Visualizations/EquityIndicators.js
src/components/Visualizations/Suppliers.js
src/layouts/pages/Blog/BlogDetail.js
src/layouts/pages/Buyer/BuyerProfile.js
src/layouts/pages/Contract/ContractDetail.js
src/layouts/pages/CountryProfile/sections/CountryInfo.js
src/layouts/pages/CountryProfile/tabs/CountrySuppliers.js
src/layouts/pages/Events/EventDetail.js
src/layouts/pages/GlobalOverview/tabs/GlobalSuppliers.js
src/layouts/pages/News/NewsDetail.js
src/layouts/pages/Resources/index.js
src/layouts/pages/Supplier/SupplierProfile.js
yarn.lock

updated date #304
in Number view

CP-304 Display the most recent contract date

---

package.json
src/components/Tables/BuyerTable.js
src/components/Tables/ContractTable.js
src/components/Tables/InsightTable.js
src/components/Tables/SupplierTable.js
src/components/Visualizations/Suppliers.js
src/constants/Default.js
src/helpers/general.js
src/hooks/useContentFilters.js
src/layouts/pages/CountryProfile/sections/CountryInfo.js
src/services/CountryService.js

CPE-154 Add the "Year" column into the insights tab

---

package.json
src/App.js
src/components/Utilities/ChartFooter.js
src/layouts/WebLayout.js

CP-379 Disable cookies acceptance in embedded visualizations

---

src/components/Tables/OverallStatisticsTable.js
src/components/Visualizations/AverageBidsPerContract.js
src/helpers/date.js

CP-381 Overall summary table additional columns
